### PR TITLE
Fixes #81 - wrong app var name for python expose

### LINKED ISSUE #81: Python expose plugin is substituting the capability in place of the FastAPI app variable name
The Python expose plugin is substituting the capability in place of the FastAPI app variable name. This causes the dispatcher to attempt to invoke API calls against the wrong variable and causes requests to fail.

### PR DESCRIPTION
**Pull request by DavidSeptimus-Klotho**
Fixes #81 by changing the `AppVarName` value set in the gateway spec back from `Capability.ID` to the name of the exported variable associated with the annotated FastAPI app.

compiled output for `py-microservices` Output after change:
image
image
image

### Standard checks

- **Unit tests**: Any special considerations?
- **Docs**: Do we need to update any docs, internal or public?
- **Backwards compatibility**: Will this break existing apps? If so, what would be the extra work required to keep them working?

### CODE REVIEW

File: pkg/lang/python/plugin_expose.go [hunk 1]
```diff
@@ -210,23 +210,23 @@ func (h *restAPIHandler) handleFile(f *core.SourceFile) (*core.SourceFile, error
...
 		}
 
-		appName = app.Identifier.Content(f.Program())
+		appVarName = app.Identifier.Content(f.Program())
 		h.RootPath = app.RootPath
 
 		gwSpec := gatewaySpec{
 			FilePath:   f.Path(),
-			AppVarName: cap.ID,
+			AppVarName: appVarName,
```
Comment (ewucc) [inline pkg/lang/python/plugin_expose.go:218]: I think this is going to break the resource validation though. iirc, the resource validation is looking for a gateway with a given gateway ID as the name

Comment (ewucc) [reply pkg/lang/python/plugin_expose.go:218]: So that might have been why this became an issue, the name was changed to fix the resource validation issue but then caused a regression w/ proxy calls

Comment (jhsinger-klotho) [inline pkg/lang/python/plugin_expose.go:218]: isnt this going to result in validation to fail again. On line 130 we call 

```python
		gw := core.NewGateway(spec.AppVarName)
```

so then wont this not match our ID? other gatewayspecs have an id field so we can track it so i dont think this prevents the warning from popping up

Comment (jhsinger-klotho) [reply pkg/lang/python/plugin_expose.go:218]: yeah same comment as below

Comment (DavidSeptimus-Klotho) [reply pkg/lang/python/plugin_expose.go:219]: yeah, I just went back and added `gatewayId` to the spec and updated this line to use that value.

**Review by jhsinger-klotho — APPROVED** [review]
