### PR TITLE
Fixes fs.js s3 read/write issues introduced by switching clients

### LINKED ISSUE #280: Regression: CloudFS Reads File Contents as a String
When migrating to v3 of the AWS client libraries, a change was introduced to `fs.js.tmpl`'s `s3_readFile` function that reads file content to a string. This leads to content mangling of binary files such as images.

impacting change:
https://github.com/KlothoPlatform/klotho/commit/2f169fdca7cb3d9a438fe2106ef1c14c24636c3c#diff-debb6bee1ab0418147f045ef7e807a5abbd72e2dbb816a003b5fd17fe92faeb1R115

### PR DESCRIPTION
**Pull request by DavidSeptimus-Klotho**
Resolves #280

- Stripped leading slashes in object paths supplied to fs functions to be more consistent with expected fs behavior (as well as the older s3fs-based implementation).
- Changed s3_readFile() to return a Promise<Buffer> by default and only returns a string if the user specifies an encoding. Additionally, an empty body results in a Promise<Void> rather than an empty string.

### Standard checks

- **Unit tests**: Any special considerations? No
- **Docs**: Do we need to update any docs, internal or public? No
- **Backwards compatibility**: Will this break existing apps? If so, what would be the extra work required to keep them working? Slim chance. Potentially breaks apps built with `v0.6.1` that using Cloud FS for JavaScript that intend to use `/` as an actual s3 object prefix or that expect `fs.readFile()` to always return a string.

### CODE REVIEW

File: pkg/lang/javascript/aws_runtime/fs.js.tmpl [hunk 1]
```diff
@@ -88,15 +88,24 @@ async function s3_writeFile(...args) {
...
+            if (args[1]?.encoding) {
+                return await streamToString(data.Body);
+            }
+            return new Promise((resolve, reject) => {
+                const stream = data.Body;
+                const chunks = [];
+                stream.on('data', chunk => chunks.push(chunk))
+                stream.once('end', () => resolve(Buffer.concat(chunks)))
+                stream.once('error', reject)
+            });
```
Comment (jhsinger-klotho) [inline pkg/lang/javascript/aws_runtime/fs.js.tmpl:106]: nit: make this reusable? Looks similar to steamToString as well but maybe nothing to pull out between the 2

**Review by jhsinger-klotho — APPROVED** [review]

File: pkg/lang/javascript/aws_runtime/fs.js.tmpl (hunk 1 above)
Comment (DavidSeptimus-Klotho) [reply pkg/lang/javascript/aws_runtime/fs.js.tmpl]: Simple enough. I hadn't even looked at the content of `streamToString`.

File: pkg/lang/javascript/aws_runtime/_fs.ts [hunk 2]
```diff
@@ -123,7 +127,7 @@ async function s3_readFile(...args) {
 async function s3_readdir(path) {
     const bucketParams: ListObjectsCommandInput = {
         Bucket: bucketName,
-        Prefix: `${path}`,
+        Prefix: stripLeadingSlashes(`${path}`),
```
Comment (gordon-klotho) [inline pkg/lang/javascript/aws_runtime/_fs.ts:130]: Did this really used to be the behaviour? If so, we broke backwards compat, then we'll be breaking backwards compat again to return it.

**Review by gordon-klotho — APPROVED** [review]
All good except the backwards compat question

File: pkg/lang/javascript/aws_runtime/_fs.ts (hunk 2 above)
Comment (DavidSeptimus-Klotho) [reply pkg/lang/javascript/aws_runtime/_fs.ts:130]: The actual behavior was actually quite a bit more complex as seen here:
https://github.com/hasnat/s3fs/blob/master/lib/utils.js

The key bit is that all the keys were normalized across host operating systems to match a specific format. Removing that from our FS breaks the expectation that you can use the Cloud FS the same as your local FS.
