### PR TITLE
Fixes target group replacement and extra logging

### LINKED ISSUE #196: sanitization for target groups is not working
error: aws:lb/targetGroup:TargetGroup resource 'alb_micro-main' has a problem: only alphanumeric characters and hyphens allowed in "name". Examine values at 'TargetGroup.Name'.

### PR DESCRIPTION
**Pull request by DavidSeptimus-Klotho**
Fixes #196

Fixes the `fix()` function for the broken rule by changing the replacement character from `_` to `-` and hides debug logging behind a flag.

### Standard checks

- **Unit tests**: Any special considerations? no
- **Docs**: Do we need to update any docs, internal or public? no
- **Backwards compatibility**: Will this break existing apps? If so, what would be the extra work required to keep them working? no

### CODE REVIEW

File: pkg/infra/pulumi_aws/iac/sanitization/aws/elb.ts [hunk 1]
```diff
@@ -56,3 +56,12 @@ export const targetGroup = {
         }
     },
 }
+
+console.log(
+    (
```
Comment (yuval-klotho) [inline pkg/infra/pulumi_aws/iac/sanitization/aws/elb.ts:61]: Just out of curiosity, what does the extra parenthesis do? (It's not a problem, I'm just wondering if there's something neat going on I don't know :) )

**Review by yuval-klotho — APPROVED** [review]

File: pkg/infra/pulumi_aws/iac/sanitization/aws/elb.ts (hunk 1 above)
Comment (DavidSeptimus-Klotho) [reply pkg/infra/pulumi_aws/iac/sanitization/aws/elb.ts:61]: 🤦 I accidentally committed the line of code I was using to reproduce the issue. That was just  a workaround to be able to invoke the fix function, which TypeScript complains about on its own because it _might be_ undefined.

Comment (gordon-klotho) [reply pkg/infra/pulumi_aws/iac/sanitization/aws/elb.ts:61]: Can use `!` for cases where you know better than the compiler to assert that it isn't undefined.

File: pkg/infra/pulumi_aws/iac/sanitization/sanitizer.ts [hunk 2]
```diff
@@ -1,6 +1,9 @@
 import Multimap = require('multimap')
 import * as sha256 from 'simple-sha256'
 
+// Set debug = true to enable additional logging
+let debug = false
```
Comment (gordon-klotho) [inline pkg/infra/pulumi_aws/iac/sanitization/sanitizer.ts:5]: nit: Would it be possible to make this a config value?

**Review by gordon-klotho — APPROVED** [review]

File: pkg/infra/pulumi_aws/iac/sanitization/sanitizer.ts (hunk 2 above)
Comment (DavidSeptimus-Klotho) [reply pkg/infra/pulumi_aws/iac/sanitization/sanitizer.ts:5]: as in pulumi config?

Comment (yuval-klotho) [reply pkg/infra/pulumi_aws/iac/sanitization/sanitizer.ts:5]: There's also `pulumi.log.[debug|info|etc]`, though I don't know exactly how they work. Maybe the verbose flag sets it?
